[package]
name = "todo-issue"
version = "0.1.0"
authors = ["Warren Galyen <wgalyen@hotmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
dialoguer = "0.4.0"
reqwest = "0.9.18"
serde = "1.0.97"